In [13]:
from request_data import get_token, request_parquet
token = get_token()
calendar = request_parquet("reports/pbi_calendar/", token)

In [14]:
calendar

shape: (122, 11)
┌────────────┬──────┬─────────────┬───────────┬───┬─────────┬────────────┬────────────┬────────────┐
│ date       ┆ year ┆ month_numbe ┆ month     ┆ … ┆ quarter ┆ quarter_nu ┆ week_numbe ┆ week_start │
│ ---        ┆ ---  ┆ r           ┆ ---       ┆   ┆ ---     ┆ mber       ┆ r          ┆ ---        │
│ str        ┆ i64  ┆ ---         ┆ str       ┆   ┆ str     ┆ ---        ┆ ---        ┆ str        │
│            ┆      ┆ i64         ┆           ┆   ┆         ┆ i64        ┆ i64        ┆            │
╞════════════╪══════╪═════════════╪═══════════╪═══╪═════════╪════════════╪════════════╪════════════╡
│ 2026-09-01 ┆ 2026 ┆ 9           ┆ September ┆ … ┆ QTR3    ┆ 3          ┆ 36         ┆ 2026-08-31 │
│ 2026-09-02 ┆ 2026 ┆ 9           ┆ September ┆ … ┆ QTR3    ┆ 3          ┆ 36         ┆ 2026-08-31 │
│ 2026-09-03 ┆ 2026 ┆ 9           ┆ September ┆ … ┆ QTR3    ┆ 3          ┆ 36         ┆ 2026-08-31 │
│ 2026-09-04 ┆ 2026 ┆ 9           ┆ September ┆ … ┆ QTR3    ┆ 3          ┆ 36         ┆ 2026-08-31 │
│ 2026-09-05 ┆ 2026 ┆ 9           ┆ September ┆ … ┆ QTR3    ┆ 3          ┆ 36         ┆ 2026-08-31 │
│ …          ┆ …    ┆ …           ┆ …         ┆ … ┆ …       ┆ …          ┆ …          ┆ …          │
│ 2026-12-27 ┆ 2026 ┆ 12          ┆ December  ┆ … ┆ QTR4    ┆ 4          ┆ 52         ┆ 2026-12-21 │
│ 2026-12-28 ┆ 2026 ┆ 12          ┆ December  ┆ … ┆ QTR4    ┆ 4          ┆ 53         ┆ 2026-12-28 │
│ 2026-12-29 ┆ 2026 ┆ 12          ┆ December  ┆ … ┆ QTR4    ┆ 4          ┆ 53         ┆ 2026-12-28 │
│ 2026-12-30 ┆ 2026 ┆ 12          ┆ December  ┆ … ┆ QTR4    ┆ 4          ┆ 53         ┆ 2026-12-28 │
│ 2026-12-31 ┆ 2026 ┆ 12          ┆ December  ┆ … ┆ QTR4    ┆ 4          ┆ 53         ┆ 2026-12-28 │
└────────────┴──────┴─────────────┴───────────┴───┴─────────┴────────────┴────────────┴────────────┘

In [ ]:
time_utilisation = request_parquet("eu-reports/pbi_time_utilisation/site=Hull/", api_key, url=URL)

shape: (122, 11)
┌────────────┬──────┬─────────────┬───────────┬───┬─────────┬────────────┬────────────┬────────────┐
│ date       ┆ year ┆ month_numbe ┆ month     ┆ … ┆ quarter ┆ quarter_nu ┆ week_numbe ┆ week_start │
│ ---        ┆ ---  ┆ r           ┆ ---       ┆   ┆ ---     ┆ mber       ┆ r          ┆ ---        │
│ str        ┆ i64  ┆ ---         ┆ str       ┆   ┆ str     ┆ ---        ┆ ---        ┆ str        │
│            ┆      ┆ i64         ┆           ┆   ┆         ┆ i64        ┆ i64        ┆            │
╞════════════╪══════╪═════════════╪═══════════╪═══╪═════════╪════════════╪════════════╪════════════╡
│ 2026-09-01 ┆ 2026 ┆ 9           ┆ September ┆ … ┆ QTR3    ┆ 3          ┆ 36         ┆ 2026-08-31 │
│ 2026-09-02 ┆ 2026 ┆ 9           ┆ September ┆ … ┆ QTR3    ┆ 3          ┆ 36         ┆ 2026-08-31 │
│ 2026-09-03 ┆ 2026 ┆ 9           ┆ September ┆ … ┆ QTR3    ┆ 3          ┆ 36         ┆ 2026-08-31 │
│ 2026-09-04 ┆ 2026 ┆ 9           ┆ September ┆ … ┆ QTR3    ┆ 3          ┆ 36         ┆ 2026-08-31 │
│ 2026-09-05 ┆ 2026 ┆ 9           ┆ September ┆ … ┆ QTR3    ┆ 3          ┆ 36         ┆ 2026-08-31 │
│ …          ┆ …    ┆ …           ┆ …         ┆ … ┆ …       ┆ …          ┆ …          ┆ …          │
│ 2026-12-27 ┆ 2026 ┆ 12          ┆ December  ┆ … ┆ QTR4    ┆ 4          ┆ 52         ┆ 2026-12-21 │
│ 2026-12-28 ┆ 2026 ┆ 12          ┆ December  ┆ … ┆ QTR4    ┆ 4          ┆ 53         ┆ 2026-12-28 │
│ 2026-12-29 ┆ 2026 ┆ 12          ┆ December  ┆ … ┆ QTR4    ┆ 4          ┆ 53         ┆ 2026-12-28 │
│ 2026-12-30 ┆ 2026 ┆ 12          ┆ December  ┆ … ┆ QTR4    ┆ 4          ┆ 53         ┆ 2026-12-28 │
│ 2026-12-31 ┆ 2026 ┆ 12          ┆ December  ┆ … ┆ QTR4    ┆ 4          ┆ 53         ┆ 2026-12-28 │
└────────────┴──────┴─────────────┴───────────┴───┴─────────┴────────────┴────────────┴────────────┘

In [2]:
import polars as pl
machine = pl.read_csv(r'..\sharepoint\reference\machine_names\site=Hull\Hull_MachineNames.csv')

In [3]:
machine

shape: (49, 4)
┌───────────────────────┬─────────────────┬─────────┬─────────────────┐
│ MachineName           ┆ Dept            ┆ Area    ┆ Product Type    │
│ ---                   ┆ ---             ┆ ---     ┆ ---             │
│ str                   ┆ str             ┆ str     ┆ str             │
╞═══════════════════════╪═════════════════╪═════════╪═════════════════╡
│ 4 Tonne               ┆ Liquids Process ┆ Liquids ┆ Liquids Process │
│ 6 Tonne               ┆ Liquids Process ┆ Liquids ┆ Liquids Process │
│ 6000L                 ┆ Liquids Process ┆ Liquids ┆ Liquids Process │
│ Analgesics Processing ┆ Dries Process   ┆ Dries   ┆ Dries Process   │
│ B1                    ┆ Liquids Pack    ┆ Liquids ┆ Bottles         │
│ …                     ┆ …               ┆ …       ┆ …               │
│ D2                    ┆ Liquids Pack    ┆ Liquids ┆ Bottles         │
│ Vacumix               ┆ Liquids Process ┆ Liquids ┆ Liquids Process │
│ D3                    ┆ Liquids Pack    ┆ Liquids ┆ Bottles         │
│ GT4                   ┆ Dries Pack      ┆ Dries   ┆ Blisters        │
│ Uhlmann               ┆ Dries Pack      ┆ Dries   ┆ BUP             │
└───────────────────────┴─────────────────┴─────────┴─────────────────┘

In [8]:
request_parquet("data/ten=reckitt/eu_report/pbi_report/report/pbi_machine_names/pbi_machine_names.parquet", token)

shape: (60, 7)
┌───────────┬─────────┬──────────────┬───────────────┬──────────────┬───────────────┬──────────────┐
│ site_name ┆ area    ┆ dept         ┆ machine_name  ┆ product_type ┆ unique_machin ┆ loaded_at    │
│ ---       ┆ ---     ┆ ---          ┆ ---           ┆ ---          ┆ e_name        ┆ ---          │
│ str       ┆ str     ┆ str          ┆ str           ┆ str          ┆ ---           ┆ datetime[ms] │
│           ┆         ┆              ┆               ┆              ┆ str           ┆              │
╞═══════════╪═════════╪══════════════╪═══════════════╪══════════════╪═══════════════╪══════════════╡
│ Hull      ┆ Liquids ┆ Liquids Pack ┆ B1            ┆ Bottles      ┆ B1-Hull       ┆ 2026-10-16   │
│           ┆         ┆              ┆               ┆              ┆               ┆ 03:52:22.386 │
│ Hull      ┆ Liquids ┆ Liquids Pack ┆ B2 Auto       ┆ Bottles      ┆ B2 Auto-Hull  ┆ 2026-10-16   │
│           ┆         ┆              ┆               ┆              ┆               ┆ 03:52:22.386 │
│ Hull      ┆ Liquids ┆ Liquids Pack ┆ B4            ┆ Bottles      ┆ B4-Hull       ┆ 2026-10-16   │
│           ┆         ┆              ┆               ┆              ┆               ┆ 03:52:22.386 │
│ Hull      ┆ Liquids ┆ Liquids Pack ┆ B6            ┆ Bottles      ┆ B6-Hull       ┆ 2026-10-16   │
│           ┆         ┆              ┆               ┆              ┆               ┆ 03:52:22.386 │
│ Hull      ┆ Dries   ┆ Dries Pack   ┆ Bosch Blister ┆ Blisters     ┆ Bosch Blister ┆ 2026-10-16   │
│           ┆         ┆              ┆ Line          ┆              ┆ Line-Hull     ┆ 03:52:22.386 │
│ …         ┆ …       ┆ …            ┆ …             ┆ …            ┆ …             ┆ …            │
│ Weinheim  ┆ Tablets ┆ Tablets      ┆ Line 2        ┆ Tablets      ┆ Line          ┆ 2026-10-16   │
│           ┆         ┆              ┆               ┆              ┆ 2-Weinheim    ┆ 03:52:22.386 │
│ Weinheim  ┆ Tablets ┆ Tablets      ┆ Line 3        ┆ Tablets      ┆ Line          ┆ 2026-10-16   │
│           ┆         ┆              ┆               ┆              ┆ 3-Weinheim    ┆ 03:52:22.386 │
│ Weinheim  ┆ Tablets ┆ Tablets      ┆ Line 4        ┆ Tablets      ┆ Line          ┆ 2026-10-16   │
│           ┆         ┆              ┆               ┆              ┆ 4-Weinheim    ┆ 03:52:22.386 │
│ Weinheim  ┆ Tablets ┆ Tablets      ┆ Line 5        ┆ Tablets      ┆ Line          ┆ 2026-10-16   │
│           ┆         ┆              ┆               ┆              ┆ 5-Weinheim    ┆ 03:52:22.386 │
│ Weinheim  ┆ Tablets ┆ Tablets      ┆ Line 6        ┆ Tablets      ┆ Line          ┆ 2026-10-16   │
│           ┆         ┆              ┆               ┆              ┆ 6-Weinheim    ┆ 03:52:22.386 │
└───────────┴─────────┴──────────────┴───────────────┴──────────────┴───────────────┴──────────────┘

In [9]:
request_parquet("data/ten=reckitt/eu_report/pbi_report/report/pbi_daily_losses/site=Hull/pbi_daily_losses_2026-10.parquet", token)

shape: (5_128, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ site_name ┆ machine_n ┆ unique_ma ┆ date      ┆ … ┆ merged    ┆ shift_nam ┆ volume_da ┆ loaded_a │
│ ---       ┆ ame       ┆ chine_nam ┆ ---       ┆   ┆ ---       ┆ e_copy    ┆ y_key     ┆ t        │
│ str       ┆ ---       ┆ e         ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆ ---       ┆           ┆   ┆           ┆ str       ┆ str       ┆ datetime │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆           ┆ [ms]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Hull      ┆ B1        ┆ B1-Hull   ┆ 2026-10-0 ┆ … ┆ B1 01/10/ ┆ ThurDay - ┆ B1 01/10/ ┆ 2026-10- │
│           ┆           ┆           ┆ 1         ┆   ┆ 2026      ┆ Red       ┆ 2026      ┆ 16 03:17 │
│           ┆           ┆           ┆           ┆   ┆ 06:00:00  ┆           ┆           ┆ :34.594  │
│ Hull      ┆ B4        ┆ B4-Hull   ┆ 2026-10-0 ┆ … ┆ B4 01/10/ ┆ ThurDay - ┆ B4 01/10/ ┆ 2026-10- │
│           ┆           ┆           ┆ 1         ┆   ┆ 2026      ┆ Red       ┆ 2026      ┆ 16 03:17 │
│           ┆           ┆           ┆           ┆   ┆ 06:00:00  ┆           ┆           ┆ :34.594  │
│ Hull      ┆ Enflex    ┆ Enflex-Hu ┆ 2026-10-0 ┆ … ┆ Enflex    ┆ Thursday  ┆ Enflex    ┆ 2026-10- │
│           ┆           ┆ ll        ┆ 1         ┆   ┆ 01/10/202 ┆ Early     ┆ 01/10/202 ┆ 16 03:17 │
│           ┆           ┆           ┆           ┆   ┆ 6         ┆ Shift     ┆ 6         ┆ :34.594  │
│           ┆           ┆           ┆           ┆   ┆ 06:00:00  ┆           ┆           ┆          │
│ Hull      ┆ Fybogel   ┆ Fybogel   ┆ 2026-10-0 ┆ … ┆ Fybogel   ┆ Thur Day  ┆ Fybogel   ┆ 2026-10- │
│           ┆ 30s       ┆ 30s-Hull  ┆ 1         ┆   ┆ 30s 01/10 ┆           ┆ 30s 01/10 ┆ 16 03:17 │
│           ┆           ┆           ┆           ┆   ┆ /2026     ┆           ┆ /2026     ┆ :34.594  │
│           ┆           ┆           ┆           ┆   ┆ 06:00:0…  ┆           ┆           ┆          │
│ Hull      ┆ Infant    ┆ Infant    ┆ 2026-10-0 ┆ … ┆ Infant    ┆ Thursday  ┆ Infant    ┆ 2026-10- │
│           ┆ Gaviscon  ┆ Gaviscon- ┆ 1         ┆   ┆ Gaviscon  ┆ Early     ┆ Gaviscon  ┆ 16 03:17 │
│           ┆           ┆ Hull      ┆           ┆   ┆ 01/10/202 ┆ Shift     ┆ 01/10/202 ┆ :34.594  │
│           ┆           ┆           ┆           ┆   ┆ 6 06:…    ┆           ┆ 6         ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Hull      ┆ SP4       ┆ SP4-Hull  ┆ 2026-10-1 ┆ … ┆ SP4 15/10 ┆ WedNight  ┆ SP4 14/10 ┆ 2026-10- │
│           ┆           ┆           ┆ 5         ┆   ┆ /2026     ┆ - Red     ┆ /2026     ┆ 16 03:17 │
│           ┆           ┆           ┆           ┆   ┆ 05:45:00  ┆           ┆           ┆ :34.594  │
│ Hull      ┆ SP8       ┆ SP8-Hull  ┆ 2026-10-1 ┆ … ┆ SP8 15/10 ┆ WedNight  ┆ SP8 14/10 ┆ 2026-10- │
│           ┆           ┆           ┆ 5         ┆   ┆ /2026     ┆ - Red     ┆ /2026     ┆ 16 03:17 │
│           ┆           ┆           ┆           ┆   ┆ 05:45:00  ┆           ┆           ┆ :34.594  │
│ Hull      ┆ GT4       ┆ GT4-Hull  ┆ 2026-10-1 ┆ … ┆ GT4 15/10 ┆ WedNight  ┆ GT4 14/10 ┆ 2026-10- │
│           ┆           ┆           ┆ 5         ┆   ┆ /2026     ┆ - Red     ┆ /2026     ┆ 16 03:17 │
│           ┆           ┆           ┆           ┆   ┆ 05:50:00  ┆           ┆           ┆ :34.594  │
│ Hull      ┆ Enflex    ┆ Enflex-Hu ┆ 2026-10-1 ┆ … ┆ Enflex    ┆ Thursday  ┆ Enflex    ┆ 2026-10- │
│           ┆           ┆ ll        ┆ 5         ┆   ┆ 15/10/202 ┆ Early     ┆ 15/10/202 ┆ 16 03:17 │
│           ┆           ┆           ┆           ┆   ┆ 6         ┆ Shift     ┆ 6         ┆ :34.594  │
│           ┆           ┆           ┆           ┆   ┆ 06:00:00  ┆           ┆           ┆          │
│ Hull      ┆ Infant    ┆ Infant    ┆ 2026-10-1 ┆ … ┆ Infant    ┆ Thursday  ┆ Infant    ┆ 2026-10- │
│           ┆ Gaviscon  ┆ Gaviscon- ┆ 5         ┆   ┆ Gaviscon  ┆ Early     ┆ Gaviscon  ┆ 16 03:17 │
│           ┆           ┆ Hull      ┆           ┆   ┆ 15/10/202 ┆ Shift     ┆ 15/10/202 ┆ :34.594  │
│           ┆           ┆           ┆           ┆   ┆ 6 06:…    ┆           ┆ 6         ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
request_parquet("data/ten=reckitt/reports/pbi_time_utilisation/site=Hull/pbi_time_utilisation_2026-10-15.parquet", token)

shape: (2, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ site_name ┆ machine_n ┆ unique_ma ┆ date      ┆ … ┆ planned_o ┆ oee_time_ ┆ all_time ┆ loaded_at │
│ ---       ┆ ame       ┆ chine_nam ┆ ---       ┆   ┆ pt_total  ┆ total     ┆ ---      ┆ ---       │
│ str       ┆ ---       ┆ e         ┆ str       ┆   ┆ ---       ┆ ---       ┆ i64      ┆ datetime[ │
│           ┆ str       ┆ ---       ┆           ┆   ┆ f64       ┆ f64       ┆          ┆ ms]       │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ Hull      ┆ B2 Line   ┆ cf4565d7d ┆ 2026-10-1 ┆ … ┆ 1440.0    ┆ 432.17419 ┆ 1440     ┆ 2026-10-1 │
│           ┆           ┆ a1e4efcbc ┆ 5         ┆   ┆           ┆ 4         ┆          ┆ 6 07:00:1 │
│           ┆           ┆ 0ea6a4814 ┆           ┆   ┆           ┆           ┆          ┆ 0.155     │
│           ┆           ┆ b8e…      ┆           ┆   ┆           ┆           ┆          ┆           │
│ Hull      ┆ GT4       ┆ bc08dae16 ┆ 2026-10-1 ┆ … ┆ 1118.0833 ┆ 841.9875  ┆ 1440     ┆ 2026-10-1 │
│           ┆           ┆ 1124f1cb5 ┆ 5         ┆   ┆ 33        ┆           ┆          ┆ 6 07:00:1 │
│           ┆           ┆ 33199f556 ┆           ┆   ┆           ┆           ┆          ┆ 0.155     │
│           ┆           ┆ 190…      ┆           ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘